id = "path-server"
name = "Path server"
version = "0.0.1"
schema_version = 1
authors = ["KunlingLio"]
description = "A Zed extension that provides path auto completion for file paths in the editor."
repository = "https://github.com/KunlingLio/path-intellisense"

[language_servers.path-server]
name = "path-server"
languages = [
  "AsciiDoc",
  "Astro",
  "Bash",
  "Biome",
  "C",
  "C#",
  "C++",
  "Clojure",
  "CSharp",
  "CSS",
  "CSV",
  "Crystal",
  "D",
  "Dart",
  "Deno",
  "Docker",
  "Elixir",
  "Elm",
  "Emmet",
  "Erlang",
  "Fish",
  "FSharp",
  "GDScript",
  "Git Commit",
  "Gleam",
  "GLSL",
  "Go",
  "GraphQL",
  "Groovy",
  "Haskell",
  "HEEX",
  "HTML",
  "Hy",
  "Idris",
  "Java",
  "JavaScript",
  "JSON",
  "JSONC",
  "Julia",
  "Kotlin",
  "LaTeX",
  "Lua",
  "Luau",
  "Makefile",
  "Markdown",
  "Nim",
  "Nix",
  "OCaml",
  "PHP",
  "Plain Text",
  "Prisma",
  "Proto",
  "PureScript",
  "Python",
  "R",
  "Racket",
  "Rego",
  "reST",
  "ReStructuredText",
  "Roc",
  "Ruby",
  "Rust",
  "Scala",
  "Scheme",
  "SCSS",
  "Shell Script",
  "SQL",
  "Svelte",
  "Swift",
  "TailwindCSS",
  "Terraform",
  "TOML",
  "TSX",
  "TypeScript",
  "Typst",
  "Uiua",
  "Vue",
  "Vue.js",
  "WIT",
  "XML",
  "YAML",
  "Yarn",
  "Zig",
]
